<?php

namespace App\Models;

use CodeIgniter\Model;

class Model_Daftar_BS extends Model {
    protected $table      = 'daftar_bs';
    protected $primaryKey = 'uuid';

    protected $useAutoIncrement = false;
    protected $allowedFields = ['uuid', 'nama'];
    /*
        uuid = generated by javascript crypto.randomUUID()
        nama = input form text
    */

}
