<?php

namespace App\Models;

use CodeIgniter\Model;

class Model_Daftar_Tipe extends Model {
    protected $table      = 'daftar_tipe';
    protected $primaryKey = 'uuid';

    protected $useAutoIncrement = false;
    protected $allowedFields = ['uuid', 'nama_tipe', 'kategori'];
    /*
        uuid = generated by javascript crypto.randomUUID()
        nama_tipe = input form text
        kategori = input form text
    */

}
