<?php

namespace App\Models;

use CodeIgniter\Model;

class Model_RKA_Tahunan extends Model {
    protected $table      = 'rka_tahunan';
    protected $primaryKey = 'uuid';

    protected $useAutoIncrement = false;
    protected $allowedFields = ['uuid', 'timestamp', 'tahun', 'nama_file', 'judul_file'];
    /*
        uuid = generated by javascript crypto.randomUUID()
        timestamp = generated by javascript Date.now()
        tanggal = input form date
        nama_file = input form text
        judul_file = input form text
    */

}
