<?php

namespace App\Models;

use CodeIgniter\Model;

class Model_User extends Model
{
    protected $table      = 'users';
    protected $primaryKey = 'uuid';

    protected $useAutoIncrement = false;
    protected $allowedFields = ['uuid', 'level', 'username', 'password', 'nama_asli', 'jabatan'];
    /*
        uuid = generated by javascript crypto.randomUUID()
        level = input form select
        username = input form text
        password = input form password
        nama_asli = input form text
        jabatan = input form text OR select
    */
}